<a href="https://colab.research.google.com/github/swaroop070305/TASK-TRAINING/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
zero=np.zeros((1,10)).reshape(2,5)
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
arr=np.arange(2,20,2)
print(arr)


[ 2  4  6  8 10 12 14 16 18]


In [ ]:
import numpy as np
arr=[2,4,5,7,10]
shapes=np.shape(arr)
print(shapes)

(5,)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
import pandas as pd
s=pd.Series((1,2,6,8,9,4,7))
print(s)
print(s.describe())
print(s.mean())
print(s.std())
print(s.min())
print(s.max())
print(s.map(lambda x:x*2))
print(s.apply(lambda x:x**4))
print(s.sort_values())
print(s.sum())
print(s.cumsum())
print(s.aggregate(['sum','mean','std']))


0    1
1    2
2    6
3    8
4    9
5    4
6    7
dtype: int64
count    7.000000
mean     5.285714
std      3.039424
min      1.000000
25%      3.000000
50%      6.000000
75%      7.500000
max      9.000000
dtype: float64
5.285714285714286
3.039423504234847
1
9
0     2
1     4
2    12
3    16
4    18
5     8
6    14
dtype: int64
0       1
1      16
2    1296
3    4096
4    6561
5     256
6    2401
dtype: int64
0    1
1    2
5    4
2    6
6    7
3    8
4    9
dtype: int64
37
0     1
1     3
2     9
3    17
4    26
5    30
6    37
dtype: int64
sum     37.000000
mean     5.285714
std      3.039424
dtype: float64


In [ ]:
import numpy as np
import pandas as pd
s=pd.Series((1,2,6,np.nan,9,4,7))
print(s)
print(s.iloc[-2])
print(s.loc[2])
print(s[s>5])


0    1.0
1    2.0
2    6.0
3    NaN
4    9.0
5    4.0
6    7.0
dtype: float64
4.0
6.0
2    6.0
4    9.0
6    7.0
dtype: float64
